# Generated by Django 5.2.2 on 2025-06-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveytask',
            name='type',
            field=models.CharField(choices=[('survey', 'Survey'), ('video', 'Watch Video'), ('link', 'Share Link'), ('lock', 'Lock Amount'), ('invest', 'Invest Amount'), ('deposit', 'Deposit & Hold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('funding', 'Funding'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('invest', 'Invest'), ('return', 'Return')], max_length=20),
        ),
    ]
